# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(877, 444)
        palette = QtGui.QPalette()
        palette.setBrush(QtGui.QPalette.Background, QtGui.QBrush(QtGui.QPixmap("./data/2/Beatiful/2-2.png")))
        MainWindow.setPalette(palette)
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(670, 10, 61, 20))
        self.label.setObjectName("label")
        self.Com_List = QtWidgets.QComboBox(self.centralwidget)
        self.Com_List.setGeometry(QtCore.QRect(740, 10, 71, 20))
        self.Com_List.setObjectName("Com_List")
        self.Com_Baud = QtWidgets.QComboBox(self.centralwidget)
        self.Com_Baud.setGeometry(QtCore.QRect(740, 40, 71, 20))
        self.Com_Baud.setObjectName("Com_Baud")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(670, 70, 51, 20))
        self.label_3.setObjectName("label_3")
        self.Com_Bytes = QtWidgets.QComboBox(self.centralwidget)
        self.Com_Bytes.setGeometry(QtCore.QRect(740, 70, 69, 22))
        self.Com_Bytes.setObjectName("Com_Bytes")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(670, 100, 54, 16))
        self.label_4.setObjectName("label_4")
        self.Com_StopBytes = QtWidgets.QComboBox(self.centralwidget)
        self.Com_StopBytes.setGeometry(QtCore.QRect(740, 100, 69, 22))
        self.Com_StopBytes.setObjectName("Com_StopBytes")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(670, 130, 54, 16))
        self.label_5.setObjectName("label_5")
        self.Com_CheckByte = QtWidgets.QComboBox(self.centralwidget)
        self.Com_CheckByte.setGeometry(QtCore.QRect(740, 130, 69, 22))
        self.Com_CheckByte.setObjectName("Com_CheckByte")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(670, 40, 54, 16))
        self.label_2.setObjectName("label_2")
        self.Com_Open = QtWidgets.QPushButton(self.centralwidget)
        self.Com_Open.setGeometry(QtCore.QRect(670, 160, 81, 23))
        self.Com_Open.setObjectName("Com_Open")
        self.Com_Refrsh = QtWidgets.QPushButton(self.centralwidget)
        self.Com_Refrsh.setGeometry(QtCore.QRect(670, 190, 171, 23))
        self.Com_Refrsh.setObjectName("Com_Refrsh")
        self.comstate_tip = QtWidgets.QLabel(self.centralwidget)
        self.comstate_tip.setGeometry(QtCore.QRect(810, 380, 54, 20))
        self.comstate_tip.setObjectName("comstate_tip")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(730, 380, 81, 20))
        self.label_10.setObjectName("label_10")
        self.Com_Close = QtWidgets.QPushButton(self.centralwidget)
        self.Com_Close.setGeometry(QtCore.QRect(760, 160, 81, 23))
        self.Com_Close.setObjectName("Com_Close")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(10, 370, 151, 23))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(170, 370, 141, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(670, 220, 111, 21))
        self.label_6.setObjectName("label_6")
        self.lcdNumber = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber.setGeometry(QtCore.QRect(780, 220, 64, 23))
        self.lcdNumber.setObjectName("lcdNumber")
        self.lcdNumber_2 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_2.setGeometry(QtCore.QRect(780, 250, 64, 23))
        self.lcdNumber_2.setObjectName("lcdNumber_2")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(670, 250, 101, 20))
        self.label_7.setObjectName("label_7")
        self.tableView = QtWidgets.QTableView(self.centralwidget)
        self.tableView.setGeometry(QtCore.QRect(10, 11, 301, 351))
        self.tableView.setObjectName("tableView")
        self.Register_Button = QtWidgets.QPushButton(self.centralwidget)
        self.Register_Button.setGeometry(QtCore.QRect(330, 370, 141, 23))
        self.Register_Button.setObjectName("Register_Button")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(510, 370, 141, 23))
        self.pushButton_3.setObjectName("pushButton_3")
        self.logicShow = QtWidgets.QLabel(self.centralwidget)
        self.logicShow.setGeometry(QtCore.QRect(13, 11, 301, 351))
        self.logicShow.setObjectName("logicShow")
        self.videoLabel = QtWidgets.QLabel(self.centralwidget)
        self.videoLabel.setGeometry(QtCore.QRect(330, 10, 321, 351))
        self.videoLabel.setObjectName("videoLabel")
        self.RegisterBox = QtWidgets.QComboBox(self.centralwidget)
        self.RegisterBox.setGeometry(QtCore.QRect(780, 310, 69, 22))
        self.RegisterBox.setObjectName("RegisterBox")
        self.DeleteButton = QtWidgets.QPushButton(self.centralwidget)
        self.DeleteButton.setGeometry(QtCore.QRect(780, 340, 71, 23))
        self.DeleteButton.setObjectName("DeleteButton")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(670, 310, 101, 21))
        self.label_8.setObjectName("label_8")
        self.selectButton = QtWidgets.QPushButton(self.centralwidget)
        self.selectButton.setGeometry(QtCore.QRect(680, 340, 75, 23))
        self.selectButton.setObjectName("selectButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 877, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actioncreater = QtWidgets.QAction(MainWindow)
        self.actioncreater.setObjectName("actioncreater")
        self.actionfinished_register = QtWidgets.QAction(MainWindow)
        self.actionfinished_register.setObjectName("actionfinished_register")
        self.actionsave = QtWidgets.QAction(MainWindow)
        self.actionsave.setObjectName("actionsave")
        self.actiondelete = QtWidgets.QAction(MainWindow)
        self.actiondelete.setObjectName("actiondelete")
        self.actionupdate = QtWidgets.QAction(MainWindow)
        self.actionupdate.setObjectName("actionupdate")
        self.actionfinish = QtWidgets.QAction(MainWindow)
        self.actionfinish.setObjectName("actionfinish")
        self.label.setBuddy(self.Com_List)
        self.label_3.setBuddy(self.Com_Bytes)
        self.label_4.setBuddy(self.Com_StopBytes)
        self.label_5.setBuddy(self.Com_CheckByte)
        self.label_2.setBuddy(self.Com_Baud)
        self.comstate_tip.setBuddy(self.Com_Open)
        self.label_8.setBuddy(self.RegisterBox)

        self.retranslateUi(MainWindow)
        self.Com_Open.clicked['bool'].connect(self.comstate_tip.update)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "人脸识别智能安控系统"))
        self.label.setText(_translate("MainWindow", "串口号："))
        self.label_3.setText(_translate("MainWindow", "数据位："))
        self.label_4.setText(_translate("MainWindow", "停止位："))
        self.label_5.setText(_translate("MainWindow", "校验位："))
        self.label_2.setText(_translate("MainWindow", "波特率："))
        self.Com_Open.setText(_translate("MainWindow", "打开串口连接"))
        self.Com_Refrsh.setText(_translate("MainWindow", "刷新串口设备"))
        self.comstate_tip.setText(_translate("MainWindow", "串口关"))
        self.label_10.setText(_translate("MainWindow", "串口运行状态："))
        self.Com_Close.setText(_translate("MainWindow", "关闭串口连接"))
        self.pushButton.setText(_translate("MainWindow", "查看访问日志"))
        self.pushButton_2.setText(_translate("MainWindow", "导出访问日志"))
        self.label_6.setText(_translate("MainWindow", "烟雾报警器值状态："))
        self.label_7.setText(_translate("MainWindow", "        其他："))
        self.Register_Button.setText(_translate("MainWindow", "开始注册用户"))
        self.pushButton_3.setText(_translate("MainWindow", "识别解锁"))
        self.logicShow.setText(_translate("MainWindow", "TextLabel"))
        self.videoLabel.setText(_translate("MainWindow", "TextLabel"))
        self.DeleteButton.setText(_translate("MainWindow", "删除用户"))
        self.label_8.setText(_translate("MainWindow", "已注册用户名称："))
        self.selectButton.setText(_translate("MainWindow", "查询用户"))
        self.actioncreater.setText(_translate("MainWindow", "register"))
        self.actionfinished_register.setText(_translate("MainWindow", "finished register"))
        self.actionsave.setText(_translate("MainWindow", "save"))
        self.actiondelete.setText(_translate("MainWindow", "delete"))
        self.actionupdate.setText(_translate("MainWindow", "update"))
        self.actionfinish.setText(_translate("MainWindow", "finish"))

